// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace AddressBook {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ContactView")]
	public partial class ContactView {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UITextView __mt_address;
		
		private MonoTouch.UIKit.UITextField __mt_email;
		
		private MonoTouch.UIKit.UITextField __mt_name;
		
		private MonoTouch.UIKit.UITextField __mt_phone;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("address")]
		private MonoTouch.UIKit.UITextView address {
			get {
				this.__mt_address = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("address")));
				return this.__mt_address;
			}
			set {
				this.__mt_address = value;
				this.SetNativeField("address", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("email")]
		private MonoTouch.UIKit.UITextField email {
			get {
				this.__mt_email = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("email")));
				return this.__mt_email;
			}
			set {
				this.__mt_email = value;
				this.SetNativeField("email", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("name")]
		private MonoTouch.UIKit.UITextField name {
			get {
				this.__mt_name = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("name")));
				return this.__mt_name;
			}
			set {
				this.__mt_name = value;
				this.SetNativeField("name", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("phone")]
		private MonoTouch.UIKit.UITextField phone {
			get {
				this.__mt_phone = ((MonoTouch.UIKit.UITextField)(this.GetNativeField("phone")));
				return this.__mt_phone;
			}
			set {
				this.__mt_phone = value;
				this.SetNativeField("phone", value);
			}
		}
	}
}
